from typing import Protocol

from app.domain.entities.category import Category
from app.domain.enums.e_transaction import TransactionType


class ICategoryRepository(Protocol):
    """
    Contrato estrutural para o repositório de categorias.
    A infra implementa sem precisar herdar daqui.
    """

    async def save(self, category: Category) -> Category: ...
    async def find_by_id(self, category_id: int) -> Category | None: ...
    async def find_by_type(self, type: TransactionType) -> list[Category]: ...
    async def list_all(self) -> list[Category]: ...
    async def update(self, category: Category) -> Category: ...
    async def delete(self, category_id: int) -> None: ...
